name: 💻 Build OpenWrt (x86_64)
on:
  workflow_dispatch:
    inputs:
      lan_addr:
        description: "设置默认 LAN 地址"
        default: "192.168.1.10"
        required: true
        type: string
      root_password:
        description: "默认 root 密码（可选，默认 password）"
        default: "password"
        required: false
        type: string
      docker:
        description: "编译 Docker"
        type: boolean
        default: true
      ssrp:
        description: "编译 ShadowSocksR Plus+"
        type: boolean
        default: true
      passwall:
        description: "编译 Passwall"
        type: boolean
        default: true
      nikki:
        description: "编译 Nikki"
        type: boolean
        default: true
      openclash:
        description: "编译 OpenClash"
        type: boolean
        default: true
      lucky:
        description: "编译 Lucky"
        type: boolean
        default: true
      oaf:
        description: "编译 OpenAppFilter"
        type: boolean
        default: true
env:
  REPO_URL: openwrt/openwrt
  REPO_BRANCH: openwrt-24.10
  CACHE_VER: v4 # 如果你想强制刷新缓存，可以修改这个值
  CONFIG_FILE: configs/x86_64.config
  DIY_SCRIPT: scripts/diy-x86_64.sh
  CLASH_KERNEL: amd64
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: X86_64
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps:
      - name: Setup environment
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          # 【重要修正】在写入配置前，先创建 ccache 配置目录
          mkdir -p $HOME/.ccache
          # 现在可以安全地写入配置文件
          echo "max_size = 5.0G" > $HOME/.ccache/ccache.conf
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Checkout Action main repository
        uses: actions/checkout@v4
        with:
          path: main-repo
      - name: Checkout OpenWrt source code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH }}
          path: openwrt
          fetch-depth: 1
      - name: Free up disk space on Runner
        run: |
          echo "Initial disk space:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          echo "Disk space after cleanup:"
          df -h
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev libssl-dev rsync jq llvm-15 clang-15 golang-go
      - name: Set up build variables
        id: setup_vars
        run: |
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          
          # 将 Commit 信息格式化并写入 GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git show -s --format='作者: %an')" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git show -s --format='时间: %ci')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git show -s --format='内容: %s')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git show -s --format='hash: %H')" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +%s)" >> $GITHUB_ENV
          
          # 获取最新稳定版 Tag
          latest_release=$(curl -s "https://api.github.com/repos/openwrt/openwrt/tags" | jq -r '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1 | sed 's/^v//')
          if [ -z "$latest_release" ]; then
            echo "::warning::Failed to fetch latest tag, using fallback."
            latest_release="24.10.x"
          fi
          echo "latest_release=$latest_release" >> $GITHUB_ENV
          echo "Latest release tag determined: $latest_release"
      - name: Cache Downloads
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: dl-${{ runner.os }}-${{ env.CACHE_VER }}-${{ hashFiles('main-repo/configs/**.config', 'main-repo/config-*.txt') }}
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ runner.os }}-${{ env.CACHE_VER }}-${{ env.REPO_BRANCH }}-${{ hashFiles('main-repo/configs/**.config', 'main-repo/config-*.txt') }}
          max-size: 5G
      - name: Install Feeds
        run: |
          cd ${{ env.OPENWRT_PATH }}
          # 假设 feeds.conf.default 文件在你的主仓库的根目录
          if [ -f "${{ github.workspace }}/main-repo/feeds.conf.default" ]; then
            cp ${{ github.workspace }}/main-repo/feeds.conf.default .
          else
            echo "::warning::feeds.conf.default not found in main-repo. Using default OpenWrt feeds."
          fi
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Load Custom Configuration & DIY Script
        env:
          LAN: ${{ github.event.inputs.lan_addr }}
          ROOT_PASSWORD: ${{ github.event.inputs.root_password }}
          ENABLE_DOCKER: ${{ github.event.inputs.docker }}
          ENABLE_SSRP: ${{ github.event.inputs.ssrp }}
          ENABLE_PASSWALL: ${{ github.event.inputs.passwall }}
          ENABLE_NIKKI: ${{ github.event.inputs.nikki }}
          ENABLE_OPENCLASH: ${{ github.event.inputs.openclash }}
          ENABLE_LUCKY: ${{ github.event.inputs.lucky }}
          ENABLE_OAF: ${{ github.event.inputs.oaf }}
        run: |
          cd ${{ env.OPENWRT_PATH }}
          
          cp ${{ github.workspace }}/main-repo/${{ env.CONFIG_FILE }} .config
          [[ "$ENABLE_DOCKER"    == "true" && -f "${{ github.workspace }}/main-repo/configs/config-docker.txt" ]] && cat ${{ github.workspace }}/main-repo/configs/config-docker.txt >> .config
          [[ "$ENABLE_SSRP"      == "true" && -f "${{ github.workspace }}/main-repo/config-ssrp.txt" ]] && cat ${{ github.workspace }}/main-repo/config-ssrp.txt >> .config
          [[ "$ENABLE_PASSWALL"  == "true" && -f "${{ github.workspace }}/main-repo/config-passwall.txt" ]] && cat ${{ github.workspace }}/main-repo/config-passwall.txt >> .config
          # ... 你可以在这里继续添加其他插件的 cat 命令 ...
          # 执行主 DIY 脚本
          chmod +x ${{ github.workspace }}/main-repo/${{ env.DIY_SCRIPT }}
          ${{ github.workspace }}/main-repo/${{ env.DIY_SCRIPT }}
          
          # 【新增部分】执行额外的核心下载脚本
          # 这两个脚本应该位于你的主仓库的 scripts/ 目录下
          # 确保脚本有可执行权限
          chmod +x ${{ github.workspace }}/main-repo/scripts/preset-mihimo-core.sh
          chmod +x ${{ github.workspace }}/main-repo/scripts/preset-adguard-core.sh
          # 执行下载
          ${{ github.workspace }}/main-repo/scripts/preset-mihimo-core.sh ${{ env.CLASH_KERNEL }}
          ${{ github.workspace }}/main-repo/scripts/preset-adguard-core.sh ${{ env.CLASH_KERNEL }}
          # 生成最终 .config
          make defconfig
          
          # 提取最终环境变量
          DEVICE_TARGET=$(grep -E "^CONFIG_TARGET_[a-zA-Z0-9_]+=" .config | grep -E "=y$" | head -n1 | sed -r 's/CONFIG_TARGET_(.*)=y/\1/' | sed -r 's/(_[a-zA-Z0-9_]+)$//')
          DEVICE_SUBTARGET=$(grep -E "^CONFIG_TARGET_${DEVICE_TARGET}_[a-zA-Z0-9_]+=" .config | grep -E "=y$" | head -n1 | sed -r "s/CONFIG_TARGET_${DEVICE_TARGET}_(.*)=y/\1/")
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          echo "IP_ADDR=${{ env.LAN }}" >> $GITHUB_ENV
      - name: Download packages
        run: |
          cd ${{ env.OPENWRT_PATH }}
          make download -j$(nproc)
      - name: Compile Firmware
        id: compile
        run: |
          cd ${{ env.OPENWRT_PATH }}
          echo -e "Starting compile with $(nproc) threads"
          make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
          echo "KERNEL=$(cat bin/targets/*/*/openwrt-*.manifest | grep '^kernel' | head -n1 | awk '{print $3}' | awk -F- '{print $2}')" >> $GITHUB_ENV
      - name: Check space usage
        if: always()
        run: df -hT
      - name: Organise files
        if: steps.compile.outputs.status == 'success'
        run: |
          cd ${{ env.OPENWRT_PATH }}/bin/targets/*/*
          rm -f sha256sums packages*
          cp ${{ env.OPENWRT_PATH }}/.config build.config
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
      - name: Upload Bin Directory (optional)
        if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-bin-${{ env.FILE_DATE }}
          path: ${{ env.OPENWRT_PATH }}/bin
      - name: Upload Firmware to Artifact
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE_PATH }}
      - name: Upload Firmware to Release
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Release ${{ env.FILE_DATE }}
          tag: ${{ env.FIRMWARE_TAG }}-${{ env.FILE_DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: ${{ env.FIRMWARE_PATH }}/*
          body: |
            **This is OpenWrt Firmware built by GitHub Actions**
            ### 📒 Firmware Information
            - 💻 **Architecture:** `${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}`
            - 🌐 **Default IP:** `${{ env.IP_ADDR }}`
            - 🔑 **Default Password:** `${{ github.event.inputs.root_password }}`
            - 🚀 **Kernel Version:** `${{ env.KERNEL }}`
            
            ### 🧊 Source Code Version
            - **Source:** `${{ env.REPO_URL }}` (Branch: `${{ env.REPO_BRANCH }}`)
            - **Latest Commit:**
              - `${{ env.COMMIT_AUTHOR }}`
              - `${{ env.COMMIT_DATE }}`
              - `${{ env.COMMIT_MESSAGE }}`
              - `${{ env.COMMIT_HASH }}`
