name: 💻 Build OpenWrt (x86_64)
on:
  workflow_dispatch:
    inputs:
      lan_addr:
        description: "设置默认 LAN 地址"
        default: "192.168.1.10"
        required: true
        type: string
      root_password:
        description: "默认 root 密码（可选，默认 password）"
        default: "password"
        required: false
        type: string
      docker:
        description: "编译 Docker"
        type: boolean
        default: true
      ssrp:
        description: "编译 ShadowSocksR Plus+"
        type: boolean
        default: true
      passwall:
        description: "编译 Passwall"
        type: boolean
        default: true
      nikki:
        description: "编译 Nikki"
        type: boolean
        default: true
      openclash:
        description: "编译 OpenClash"
        type: boolean
        default: true
      lucky:
        description: "编译 Lucky"
        type: boolean
        default: true
      oaf:
        description: "编译 OpenAppFilter"
        type: boolean
        default: true
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-24.10
  CACHE_VER: v5
  CONFIG_FILE: configs/x86_64.config
  DIY_SCRIPT: scripts/diy-x86_64.sh
  CLASH_KERNEL: amd64
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: X86_64
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    # 【优化】为所有后续步骤设置默认工作目录
    defaults:
      run:
        working-directory: ./openwrt
    steps:
      - name: Setup environment
        # 【优化】此步骤在工作目录之外执行
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          mkdir -p $HOME/.ccache
          echo "max_size = 5.0G" > $HOME/.ccache/ccache.conf
        working-directory: ${{ github.workspace }}
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      # 【关键修正 1】我们只检出一次主仓库（包含脚本和配置），以简化路径。
      - name: Checkout Action main repository
        uses: actions/checkout@v4
        working-directory: ${{ github.workspace }}
      # 【关键修正 2】使用 git clone 来拉取 OpenWrt 源码，确保历史记录完整。
      - name: Clone OpenWrt source code
        id: clone_source
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt -b openwrt-24.10 openwrt
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          # 将 Commit 信息格式化并写入 GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git show -s --format='作者: %an')" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git show -s --format='时间: %ci')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git show -s --format='内容: %s')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git show -s --format='hash: %H')" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +%s)" >> $GITHUB_ENV
          # 获取最新稳定版 Tag
          latest_release=$(curl -s "https://api.github.com/repos/openwrt/openwrt/tags" | jq -r '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1 | sed 's/^v//')
          if [ -z "$latest_release" ]; then
            echo "::warning::Failed to fetch latest tag, using fallback."
            latest_release="24.10.x"
          fi
          echo "latest_release=$latest_release" >> $GITHUB_ENV
          echo "Latest release tag determined: $latest_release"
        working-directory: ${{ github.workspace }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev clang llvm golang-go
        working-directory: ${{ github.workspace }}
      - name: Cache Downloads
        uses: actions/cache@v4
        with:
          path: ./openwrt/dl
          key: dl-${{ runner.os }}-${{ env.CACHE_VER }}-${{ hashFiles('configs/**.config', 'config-*.txt') }}
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ runner.os }}-${{ env.CACHE_VER }}-${{ env.REPO_BRANCH }}-${{ hashFiles('configs/**.config', 'config-*.txt') }}
          max-size: 5G
      - name: Install Feeds
        run: |
          if [ -f "${{ github.workspace }}/feeds.conf.default" ]; then
            cp ${{ github.workspace }}/feeds.conf.default ./feeds.conf.default
          else
            echo "::warning::feeds.conf.default not found. Using default OpenWrt feeds."
          fi
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Load Custom Configuration & DIY Script
        env:
          LAN: ${{ github.event.inputs.lan_addr }}
          ROOT_PASSWORD: ${{ github.event.inputs.root_password }}
          ENABLE_DOCKER: ${{ github.event.inputs.docker }}
          ENABLE_SSRP: ${{ github.event.inputs.ssrp }}
          ENABLE_PASSWALL: ${{ github.event.inputs.passwall }}
          ENABLE_NIKKI: ${{ github.event.inputs.nikki }}
          ENABLE_OPENCLASH: ${{ github.event.inputs.openclash }}
          ENABLE_LUCKY: ${{ github.event.inputs.lucky }}
          ENABLE_OAF: ${{ github.event.inputs.oaf }}
        run: |
          # 【路径优化】直接从工作区根目录复制文件
          cp ${{ github.workspace }}/${{ env.CONFIG_FILE }} .config
          
          # 【路径优化】现在所有自定义配置都在工作区根目录
          [[ "$ENABLE_DOCKER"    == "true" && -f "${{ github.workspace }}/configs/config-docker.txt" ]] && cat ${{ github.workspace }}/configs/config-docker.txt >> .config
          [[ "$ENABLE_SSRP"      == "true" && -f "${{ github.workspace }}/config-ssrp.txt" ]] && cat ${{ github.workspace }}/config-ssrp.txt >> .config
          [[ "$ENABLE_PASSWALL"  == "true" && -f "${{ github.workspace }}/config-passwall.txt" ]] && cat ${{ github.workspace }}/config-passwall.txt >> .config
          chmod +x ${{ github.workspace }}/${{ env.DIY_SCRIPT }}
          ${{ github.workspace }}/${{ env.DIY_SCRIPT }}
          
          chmod +x ${{ github.workspace }}/scripts/preset-mihimo-core.sh
          chmod +x ${{ github.workspace }}/scripts/preset-adguard-core.sh
          ${{ github.workspace }}/scripts/preset-mihimo-core.sh ${{ env.CLASH_KERNEL }}
          ${{ github.workspace }}/scripts/preset-adguard-core.sh ${{ env.CLASH_KERNEL }}
          
          make defconfig
          
          DEVICE_TARGET=$(grep -E "^CONFIG_TARGET_[a-zA-Z0-9_]+=" .config | grep -E "=y$" | head -n1 | sed -r 's/CONFIG_TARGET_(.*)=y/\1/' | sed -r 's/(_[a-zA-Z0-9_]+)$//')
          DEVICE_SUBTARGET=$(grep -E "^CONFIG_TARGET_${DEVICE_TARGET}_[a-zA-Z0-9_]+=" .config | grep -E "=y$" | head -n1 | sed -r "s/CONFIG_TARGET_${DEVICE_TARGET}_(.*)=y/\1/")
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          echo "IP_ADDR=${LAN}" >> $GITHUB_ENV
      - name: Download packages
        run: make download -j$(nproc)
      - name: Compile Firmware
        id: compile
        run: |
          echo -e "Starting compile with $(nproc) threads"
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
          echo "KERNEL=$(cat bin/targets/*/*/openwrt-*.manifest | grep '^kernel' | head -n1 | awk '{print $3}' | awk -F- '{print $2}')" >> $GITHUB_ENV
      # ... 后续的上传步骤保持不变，因为它们依赖于 GITHUB_ENV 中的变量，其设置是正确的 ...
      - name: Check space usage
        if: always()
        run: df -hT
        working-directory: ${{ github.workspace }} # 这个步骤可以在任何地方运行
      - name: Organise files
        if: steps.compile.outputs.status == 'success'
        run: |
          cd bin/targets/*/*
          rm -f sha256sums packages*
          cp ../../../../.config build.config # 调整 .config 的相对路径
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
      - name: Upload Bin Directory (optional)
        if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-bin-${{ env.FILE_DATE }}
          path: ${{ env.OPENWRT_PATH }}/bin
      - name: Upload Firmware to Artifact
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE_PATH }}
      - name: Upload Firmware to Release
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Release ${{ env.FILE_DATE }}
          tag: ${{ env.FIRMWARE_TAG }}-${{ env.FILE_DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: ${{ env.FIRMWARE_PATH }}/*
          body: |
            **This is OpenWrt Firmware built by GitHub Actions**
            ### 📒 Firmware Information
            - 💻 **Architecture:** `${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}`
            - 🌐 **Default IP:** `${{ env.IP_ADDR }}`
            - 🔑 **Default Password:** `${{ github.event.inputs.root_password }}`
            - 🚀 **Kernel Version:** `${{ env.KERNEL }}`
            
            ### 🧊 Source Code Version
            - **Source:** `${{ env.REPO_URL }}` (Branch: `${{ env.REPO_BRANCH }}`)
            - **Latest Commit:**
              - `${{ env.COMMIT_AUTHOR }}`
              - `${{ env.COMMIT_DATE }}`
              - `${{ env.COMMIT_MESSAGE }}`
              - `${{ env.COMMIT_HASH }}`
